version: '3.7'
services:
  data-distribution-ms:
    container_name: data-distribution-ms-container
    build:
      context: data-distribution-ms/.
    image: abhaystoic/data-distribution-ms:latest
    restart: 'no'
    volumes:
      - ./data-distribution-ms/data/mongodb:/data/db
      - ./data-distribution-ms/data/mongoconfig:/data/configdb
      - ./data-distribution-ms/celery-beat-logs:/celery-beat-logs
    environment:
      - MONGO_INITDB_DATABASE=news
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - 27018:27017
      - 5673:5672
      - 15673:15672
    # entrypoint: ./data-distribution-ms/scripts/docker-entrypoint.sh

  # worker:
  #   container_name: celery-worker
  #   build: data-distribution-ms/.
  #   image: &img worker
  #   command: celery worker -A src/fetch_headlines --loglevel=info
  #   depends_on:
  #     - beat
  #     - rabbitmq
  #   restart: 'no'

  # beat:
  #   container_name: celery-beat
  #   build: data-distribution-ms/.
  #   image: *img
  #   command: celery -A src/fetch_headlines beat --loglevel=info -s ./celery-beat-logs/
  #   depends_on:
  #     - rabbitmq
  #   restart: 'no'
  #   volumes: 
  #     - ./celery-beat-logs:/celery-beat-logs

  # rabbitmq:
  #   image: rabbitmq:3.8.3
  #   container_name: rabbitmq-news-data-distribution

  # mongodb:
  #   image: mongo:4.2.5-bionic
  #   container_name: news-mongo-db
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_DATABASE=news
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=admin123
  #   volumes:
  #     - ./data/mongodb:/data/db
  #     - ./data/mongoconfig:/data/configdb
