version: '3.7'
services:
  data-distribution-ms:
    container_name: data-distribution-ms-container
    privileged: true
    build:
      context: data-distribution-ms/.
    image: abhaystoic/data-distribution-ms:latest
    restart: 'unless-stopped'
    volumes:
      - ~/docker-data/data-distribution-ms/data/mongodb:/data/db
      - ~/docker-data/data-distribution-ms/data/mongoconfig:/data/configdb
      - ~/docker-data/data-distribution-ms/celery-beat-logs:/celery-beat-logs
    environment:
      - MONGO_INITDB_DATABASE=news
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - 27018:27017
      - 5673:5672
      - 15673:15672
    networks:
      - stumped-back
    depends_on: 
      - headlines-ms
      - covid19-ms
      - all-news-ms
  
  headlines-ms:
    container_name: headlines-ms-container
    privileged: true
    build:
      context: headlines-ms/.                                                                                                                                                                                                                                                                                                                                 
    image: abhaystoic/headlines-ms:latest
    restart: 'unless-stopped'
    volumes:
      - ~/docker-data/headlines-ms/www:/var/www
      - ~/docker-data/headlines-ms/data/mongodb:/data/db
      - ~/docker-data/headlines-ms/data/mongoconfig:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=headline
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - 5001:80
      - 5004:5000
      - 27019:27017
    networks:
      - stumped-back
  
  covid19-ms:
    container_name: covid19-ms-container
    privileged: true
    build:
      context: covid19-ms/.                                                                                                                                                                                                                                                                                                                                 
    image: abhaystoic/covid19-ms:latest
    restart: 'unless-stopped'
    volumes:
      - ~/docker-data/covid19-ms/www:/var/www
      - ~/docker-data/covid19-ms/data/mongodb:/data/db
      - ~/docker-data/covid19-ms/data/mongoconfig:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=covid19
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - 5002:80
      - 5006:5000
      - 27020:27017
    networks:
      - stumped-back
  
  all-news-ms:
    container_name: all-news-ms-container
    privileged: true
    build:
      context: all-news-ms/.                                                                                                                                                                                                                                                                                                                                 
    image: abhaystoic/all-news-ms:latest
    restart: 'unless-stopped'
    volumes:
      - ~/docker-data/all-news-ms/www:/var/www
      - ~/docker-data/all-news-ms/data/mongodb:/data/db
      - ~/docker-data/all-news-ms/data/mongoconfig:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=all_news
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - 5003:80
      - 5007:5000
      - 27021:27017
    networks:
      - stumped-back
  
  elastic-search-ms:
    container_name: elastic-search-ms-container
    privileged: true
    build:
      context: elastic-search-ms/.
    image: abhaystoic/elastic-search-ms:latest
    environment:
      - node.name=elastic-search
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elastic-search
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.bind_host=0.0.0.0
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/docker-data/elastic-search:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - stumped-back

networks:
  stumped-back:
    driver: bridge
