version: '3.7'
services:
  data-distribution-ms:
    container_name: data-distribution-ms-container
    build:
      context: data-distribution-ms/.
    image: abhaystoic/data-distribution-ms:latest
    restart: 'no'
    volumes:
      - ./data-distribution-ms/data/mongodb:/data/db
      - ./data-distribution-ms/data/mongoconfig:/data/configdb
      - ./data-distribution-ms/celery-beat-logs:/celery-beat-logs
    environment:
      - MONGO_INITDB_DATABASE=news
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - 27018:27017
      - 5673:5672
      - 15673:15672
