version: '3.7'
services:
  data-distribution-ms:
    container_name: data-distribution-ms-container
    logging:
      options:
        max-size: 10m
    privileged: true
    build:
      context: data-distribution-ms/.
    image: abhaystoic/data-distribution-ms:latest
    deploy:
      resources:
        limits:
          memory: 200M
    restart: 'unless-stopped'
    volumes:
      - ~/docker-data/data-distribution-ms/data/mongodb:/data/db
      - ~/docker-data/data-distribution-ms/data/mongoconfig:/data/configdb
      - ~/docker-data/data-distribution-ms/celery-beat-logs:/celery-beat-logs
    environment:
      - NEWS_API_KEY_BACKUP=$NEWS_API_KEY_BACKUP
      - NEWS_API_KEY_DEV=$NEWS_API_KEY_DEV
      - NEWS_API_KEY_PROD=$NEWS_API_KEY_PROD
      - MONGODB_PORT=$MONGODB_PORT
      - MONGO_INITDB_DATABASE=news
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_USER=$MONGO_USER
      - MONGO_PWD=$MONGO_PWD
      - PIKA_USER_HEADLINES_MS_CONTAINER=$PIKA_USER_HEADLINES_MS_CONTAINER
      - PIKA_PWD_HEADLINES_MS_CONTAINER=$PIKA_PWD_HEADLINES_MS_CONTAINER
      - PIKA_USER_COVID19_MS_CONTAINER=$PIKA_USER_COVID19_MS_CONTAINER
      - PIKA_PWD_COVID19_MS_CONTAINER=$PIKA_PWD_COVID19_MS_CONTAINER
      - PIKA_USER_ALL_NEWS_MS_CONTAINER=$PIKA_USER_ALL_NEWS_MS_CONTAINER
      - PIKA_PWD_ALL_NEWS_MS_CONTAINER=$PIKA_PWD_ALL_NEWS_MS_CONTAINER
    env_file: .env
    ports:
      - 27018:$MONGODB_PORT
      - 5673:5672
      - 15673:15672
    networks:
      stumped-back:
        ipv4_address: $IPV4_ADDRESS_DATA_DISTRIBUTION_MS_CONTAINER
    depends_on: 
      - headlines-ms
      - covid19-ms
      - all-news-ms
  
  headlines-ms:
    container_name: headlines-ms-container
    logging:
      options:
        max-size: 10m
    privileged: true
    build:
      context: headlines-ms/.                                                                                                                                                                                                                                                                                                                                 
    image: abhaystoic/headlines-ms:latest
    deploy:
      resources:
        limits:
          memory: 200M
    restart: 'unless-stopped'
    volumes:
      - ~/docker-data/headlines-ms/www:/var/www
      - ~/docker-data/headlines-ms/data/mongodb:/data/db
      - ~/docker-data/headlines-ms/data/mongoconfig:/data/configdb
    environment:
      - MONGODB_PORT=$MONGODB_PORT
      - MONGO_INITDB_DATABASE=headline
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_USER=$MONGO_USER
      - MONGO_PWD=$MONGO_PWD
      - PIKA_USER_HEADLINES_MS_CONTAINER=$PIKA_USER_HEADLINES_MS_CONTAINER
      - PIKA_PWD_HEADLINES_MS_CONTAINER=$PIKA_PWD_HEADLINES_MS_CONTAINER
    env_file: .env
    ports:
      - 5001:80
      - 5004:5000
      - 27019:$MONGODB_PORT
    networks:
      stumped-back:
        ipv4_address: $IPV4_ADDRESS_HEADLINES_MS_CONTAINER
  
  covid19-ms:
    container_name: covid19-ms-container
    logging:
      options:
        max-size: 10m
    privileged: true
    build:
      context: covid19-ms/.                                                                                                                                                                                                                                                                                                                                 
    image: abhaystoic/covid19-ms:latest
    deploy:
      resources:
        limits:
          memory: 200M
    restart: 'unless-stopped'
    volumes:
      - ~/docker-data/covid19-ms/www:/var/www
      - ~/docker-data/covid19-ms/data/mongodb:/data/db
      - ~/docker-data/covid19-ms/data/mongoconfig:/data/configdb
    environment:
      - MONGODB_PORT=$MONGODB_PORT
      - MONGO_INITDB_DATABASE=covid19
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_USER=$MONGO_USER
      - MONGO_PWD=$MONGO_PWD
      - PIKA_USER_COVID19_MS_CONTAINER=$PIKA_USER_COVID19_MS_CONTAINER
      - PIKA_PWD_COVID19_MS_CONTAINER=$PIKA_PWD_COVID19_MS_CONTAINER
    env_file: .env
    ports:
      - 5002:80
      - 5006:5000
      - 27020:$MONGODB_PORT
    networks:
      stumped-back:
        ipv4_address: $IPV4_ADDRESS_COVID19_MS_CONTAINER
  
  all-news-ms:
    container_name: all-news-ms-container
    logging:
      options:
        max-size: 10m
    privileged: true
    build:
      context: all-news-ms/.                                                                                                                                                                                                                                                                                                                                 
    image: abhaystoic/all-news-ms:latest
    deploy:
      resources:
        limits:
          memory: 200M
    restart: 'unless-stopped'
    volumes:
      - ~/docker-data/all-news-ms/www:/var/www
      - ~/docker-data/all-news-ms/data/mongodb:/data/db
      - ~/docker-data/all-news-ms/data/mongoconfig:/data/configdb
    environment:
      - MONGODB_PORT=$MONGODB_PORT
      - MONGO_INITDB_DATABASE=all_news
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_USER=$MONGO_USER
      - MONGO_PWD=$MONGO_PWD
      - PIKA_USER_ALL_NEWS_MS_CONTAINER=$PIKA_USER_ALL_NEWS_MS_CONTAINER
      - PIKA_PWD_ALL_NEWS_MS_CONTAINER=$PIKA_PWD_ALL_NEWS_MS_CONTAINER
    env_file: .env
    ports:
      - 5003:80
      - 5007:5000
      - 27021:$MONGODB_PORT
    networks:
      stumped-back:
        ipv4_address: $IPV4_ADDRESS_ALL_NEWS_MS_CONTAINER
  
  elastic-search-ms:
    container_name: elastic-search-ms-container
    logging:
      options:
        max-size: 10m
    privileged: true
    build:
      context: elastic-search-ms/.
    image: abhaystoic/elastic-search-ms:latest
    deploy:
      resources:
        limits:
          memory: 200M
    restart: 'unless-stopped'
    environment:
      - node.name=elastic-search
      - cluster.name=news-elasticsearch-cluster
      - cluster.initial_master_nodes=elastic-search
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.bind_host=0.0.0.0
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/docker-data/elastic-search:/usr/share/elasticsearch/data
    env_file: .env
    ports:
      - 9200:9200
    networks:
      stumped-back:
        ipv4_address: $IPV4_ADDRESS_ELASTIC_SEARCH_MS_CONTAINER

networks:
  stumped-back:
    driver: bridge
    ipam:
      config:
      - subnet: $BRIDGE_SUBNET
