FROM docker.elastic.co/elasticsearch/elasticsearch:7.10.1
COPY --chown=elasticsearch:elasticsearch elasticsearch.yml /usr/share/elasticsearch/config/

# Expose the default Elasticsearch port
EXPOSE 9200

# RUN yum install vim-enhanced -y  
